# Generated by Django 4.0.1 on 2022-05-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('nombreCuenta', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('duracion', models.CharField(max_length=20)),
                ('fechaCompra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('IDcuenta', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descuento', models.IntegerField()),
                ('fechaOferta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=14)),
            ],
        ),
    ]
