# Generated by Django 4.0.5 on 2022-06-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_remove_cuenta_fechacompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('nombreCuenta', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='nombre de la cuenta')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('duracion', models.CharField(max_length=20, verbose_name='Duracion Cuenta')),
            ],
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='IDcuenta',
            new_name='tipoCuenta',
        ),
        migrations.AddField(
            model_name='usuario',
            name='clave',
            field=models.CharField(default=2, max_length=30, verbose_name='contraseña'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=14, verbose_name='Telefono'),
        ),
    ]
