# Generated by Django 4.0.5 on 2022-06-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0003_cuentas_delete_cuenta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='clave',
        ),
    ]
